### ISSUE TITLE
Какие компоненты брать для схемы?

### ISSUE THREAD

**Issue by AlexanderKa1** [LukyanovAnatoliy/WaterMeter_v2#1]
Привет! 
     Какие компоненты необходимо приобрести что бы собрать аналогичное устройство? В документации что то не нашел перечня. %(

**Comment by LukyanovAnatoliy** [comment]
1. ESP-03 - 1шт
2. Резисторы 6.8 кОм - 5шт
3. Резисторы 330 Ом - 2шт
4. Конденсатор 1мкФ - 1шт
5. Танталовый конденсатор 33мкФ - 1шт
6. Кнопка - 1шт
7. Светодиоды - 2 шт
8. Разъем micro USB - 1шт
9. Разъем mini USB - 1шт
10. LM1117 3.3B - 1шт
11. Разъем RJ9 - 2шт
12. Джампер - 1шт
13. PLS штырьки 2*1 - 1 шт

Плату заказать можно здесь http://dirtypcbs.com/store/designer/details/10652/978/watermeter-v2-zip
