### ISSUE TITLE
Новый функционал. Автоматическая передача показаний через СМС

### ISSUE THREAD

**Issue by farcop** [LukyanovAnatoliy/WaterMeter_v2#2]
Есть возможность полностью автоматизировать передачу показаний счетчиков воды в Москве.

Необходимо реализовать возможность автоматической передачи показании счетчиков раз в месяц посредством СМС на короткий номер 7377.
Подробнее тут https://dit.mos.ru/apps/serv/gkh_water

Т.к. все сервисы отправки СМС через Интернет не поддерживают отправку на короткие номера, то необходимо доработать аппаратную часть, добавив в нее модуль GSM.
Например такой http://mcustore.ru/store/moduli-svyazi/modul-gsm-gprs-na-sim800l/

Для событий отправки СМС и прочих вызовов "по таймеру" можно использовать функционал модуля cron http://nodemcu.readthedocs.io/en/master/en/modules/cron/
Например, вызов раз в месяц каждое 15 число.
```Lua
cron.schedule("* * 15 * *", function(em) 
)
```

**Comment by LukyanovAnatoliy** [comment]
Добавление GSM модуля сильно удорожит устройство. Сейчас его себестоимость меньше чем стоимость одного GSM модуля. По опыту работы с SIM900 для него еще нужно хорошее питание. Лучше это реализовать в приложении. Сделаю во второй его версии.

**Comment by farcop** [comment]
В приложении не получится, увы.
Я не знаю ни одного провайдера, который позволяет отправлять СМС на короткие номера.

Цель проекта получить функционально законченное устройство, а не максимально дешевое ИМХО. Просто отсылка СМС себе на мобильный - это полумера. Задача полностью автоматизировать к.м.к.

**Comment by LukyanovAnatoliy** [comment]
Отсылка смс на мобильный и не подразумевается. Приложение всегда в курсе какие сейчас показания, плюс на телефоне уже есть симкарта и не нужно держать дополнительную ради отправки 1 смс в месяц. Поэтому, если на телефоне не запрещена отправка смс на короткие номера, то все пройдет хорошо. 

Использование GSM оправдано там, где нет возможности подключиться к WiFi. Например на даче. Но тогда нам уже не нужен ESP и достаточно атмеги + GSM модуль. На это тоже есть планы.

**Comment by farcop** [comment]
Тогда вопрос: Как информация из устройства попадает на телефон и как телефон отсылает СМС на короткий номер?
Не понятна степень автоматизации.

**Comment by LukyanovAnatoliy** [comment]
Устройство отсылает данные на сервер thingspeak.com. Для телефона есть приложение [Учет потребления воды](https://play.google.com/store/apps/details?id=lav.watermeter). Приложение тянет данные показаний с сервера и отображает. В приложении уже можно реализовать что угодно. Можно сделать несколькими вариантами:
1. отправка по кнопке
2. показывать уведомление и отправка после подтверждения
3. и автоматическая отправка по расписанию с последующим уведомлением(не на всех устройствах)

**Comment by farcop** [comment]
Однако.
У меня iPhone.

**Comment by farcop** [comment]
Сейчас у меня работает так.
Железка постит в thingspeak.com, там же в Apps создан TimeControl, который дергает ThingHTTP в котором выполняется отсылка СМС через POST на sms.ru. Значения последних показаний пробрасываются
api_id=XXXXXXX&to=YYYYYYYY&text=вода добавить %%channel_224343_field_2%% %%channel_224343_field_4%%

Но TimeControl умеет шедулировать еженедельно. Ежемесячно - не умеет.
Но2 потом каждое четвертое СМС я руками пересылаю на 7377.

**Comment by LukyanovAnatoliy** [comment]
До iPhone у меня пока руки не дошли и видимо дойдут не скоро. 

Ваша идея мне понятна. Но пока я не готов ее реализовывать по ряду причин. Если появится нормальное апи(не через смс), то я его сразу реализую.

**Comment by farcop** [comment]
"Нормальное" API еще долго не появится, если вообще появится.

Ок. Закрывайте ишью.
